language: c

script: "./configure --enable-dummy-graphics --enable-lisp-graphics --enable-curses-graphics --enable-x11-graphics --enable-tty-graphics && make all check"

compiler:
  - gcc
  - clang

os:
  - linux

env:
  - CFLAGS='-O2 -Wall -Wextra -fno-common -Werror=format -Werror=return-type -Werror=uninitialized -Werror=implicit-function-declaration' LFLAGS=-fno-common

addons:
  apt:
    packages:
      - check
      - libx11-dev
      - libxaw7-dev
      - xfonts-utils

notifications:
  irc:
    channels: "chat.freenode.net#unnethack"
    use_notice: true
    skip_join: true
  email:
    on_success: always
